utils::globalVariables(c(
     "%", ".", ":=", "A", "A.3.1_all", "A.3.1_NUTS2", "A.3.3_all",
     "A.3.3_NUTS2", "A.4.3_all", "A.4.3_NUTS2", "A.4.5_all", "A.4.5_NUTS2",
     "A.5.1_all", "A.5.1_NUTS2", "activity", "AG_DM_T", "AGR_T", "allocation_key",
     "alpha", "ALU", "AN", "Animal_cat", "area_feed_produced", "area_feed_purchased",
     "area_ha_anim", "area_ha_anim_all", "area_ha_anim_NUTS2", "area_ha_livcat",
     "area_ha_perm_grass", "area_ha_temp_grass", "Area_T", "AROPAJ_DMI_t_LU_y",
     "Ash", "ASH", "Ash_p100", "Ash_pc", "Ash_t_livcat", "avrg_FADN_yield",
     "avrg_feed", "avrg_output", "avrg_yield_crop", "AWMS", "BGR_T",
     "Bo", "BV_loc", "BV_LU", "BV_norm", "BVI_ha", "BVI_ha_all", "BVI_ha_NUTS2",
     "BVI_t", "BVI_t_all", "BVI_t_NUTS2", "BW", "C", "C_preg", "Ca",
     "Cereales", "Cfi", "CH4_EF_Ym", "CH4_enteric_kgCH4", "CH4_enteric_kgCO2e_livcat",
     "CH4_MM_kgCO2e_livcat", "CH4_producing_potential_(Bo)(2)_(average)",
     "climate_region", "CN", "code", "Comment", "condition_species",
     "condition_tech", "correction_ratio", "COUNTRY", "country_FADN",
     "Country_ISO_3166_1_A3", "cow_pop", "CP", "CP_p100", "CP_pc",
     "CP_t_livcat", "crop_diversity", "crop_ghg_diesel_remain_kgCO2e",
     "crop_ghg_diesel_tillage_kgCO2e", "crop_ghg_elec_kgCO2e", "crop_ghg_ferti_prod_kgCO2e",
     "crop_ghg_heat_fuel_kgCO2e", "crop_N2O_ATD_kgCO2e", "crop_N2O_d_kgCO2e",
     "crop_N2O_L_kgCO2e", "Crop_T", "Cultures_developpees_5", "DE_pc",
     "default_avrg_yield_crop", "default_crop_yield", "default_EF3",
     "default_forage_prod", "default_forage_yield", "delta", "Departement",
     "DESCRIPTION", "diesel_l", "diesel_MJ", "diesel_remain_MJ", "diesel_tillage_l",
     "diesel_tillage_tot_l", "diesel_tillage_tot_MJ", "diesel_v",
     "DM_kg_anim", "DM_t_anim", "DM_t_anim_all", "DM_t_anim_NUTS2",
     "DM_t_livcat", "DMI_t_LU_y", "Dont_ble_tendre", "Dont_mais_grain",
     "Dont_orge", "Dont_tourteau_de_soja", "Dry_Matter_Digestibility_pct",
     "ecoalim_total_ghg_per_t", "econ_alloc_ratio_farm", "econ_alloc_ratio_heating_fuel",
     "econ_alloc_ratio_herd", "econ_alloc_ratio_herd_activity", "EF",
     "EF_CR", "EF_fuel_CO2", "EF_fuel_CO2_kgCO2MJ", "EF_MY", "EF_ON",
     "EF_OS", "EF_PRP", "EF_SN", "EF_SOM", "EF_Ym", "EF3", "EF4",
     "EF5", "elec_kWh", "elec_V", "EPK_ferti_crop_name", "EPK_Nmin",
     "epsilon", "euro_kWh", "euros_t", "euros_t_cy", "euros_t_y",
     "EUROSTAT_feedstuff", "F_CR", "F_ON", "F_OS", "F_PRP", "F_SN",
     "F_SOM", "FADN_code_description", "FADN_code_feed", "FADN_code_letter_output",
     "farm_ghg_diesel_kgCO2e", "farm_ghg_diesel_remain_kgCO2e", "farm_ghg_elec_kgCO2e",
     "farm_ghg_heat_fuel_kgCO2e", "farm_ghge_herd_kgCO2e_livcat",
     "farm_t_DM", "farm_total_CH4_kgCO2e", "farm_total_CO2_kgCO2e",
     "farm_total_ghge_kgCO2e", "farm_total_N2O_kgCO2e", "farm_use_e",
     "Feed_Description", "feed_farm_total_ghg_crop_kgCO2e_livcat",
     "feed_herd_prod_sales_e", "feed_origin", "feed_prod_t_livcat",
     "feed_produced_onfarm", "feed_pseudofarm_total_ghg_crop_kgCO2e_livcat",
     "feed_purch_t_livcat", "feed_purch_value", "feed_purch_value_share",
     "feed_t", "feed_t_crop_total", "feed_t_DM", "feed_tables", "feed_type",
     "final_price_heat", "final_price_road", "first_common", "frac_Gas_MS",
     "Frac_GASF", "Frac_GASM", "Frac_leach_H", "frac_leach_MS", "Frac_renew_T",
     "from_livestock_category", "GE", "GE_grazed", "GE_IPCC_MJ_anim_day",
     "GE_kcal_kg", "GE_kcal_livcat", "GE_MJ_anim", "GE_MJ_livcat",
     "ghg_diesel_remain_kgCO2e", "ghg_diesel_remain_kgCO2e_act_livcat",
     "ghg_diesel_remain_kgCO2e_activity", "ghg_diesel_remain_kgCO2e_livcat",
     "ghg_diesel_remain_kgCO2e_output", "ghg_diesel_tillage_kgCO2e",
     "ghg_diesel_tillage_kgCO2e_output", "ghg_elec_kgCO2e", "ghg_elec_kgCO2e_act_livcat",
     "ghg_elec_kgCO2e_activity", "ghg_elec_kgCO2e_livcat", "ghg_elec_kgCO2e_output",
     "ghg_ferti_prod_kgCO2e", "ghg_heat_fuel_kgCO2e", "ghg_heat_fuel_kgCO2e_act_livcat",
     "ghg_heat_fuel_kgCO2e_activity", "ghg_heat_fuel_kgCO2e_livcat",
     "ghg_heat_fuel_kgCO2e_output", "grazed_GE_MJ", "Group", "heating_fuels_l",
     "heating_fuels_MJ", "heating_fuels_v", "herd_CH4_enteric_kgCO2e",
     "herd_CH4_MM_kgCO2e", "herd_feed_farm_ghg_diesel_remain_kgCO2e",
     "herd_feed_farm_ghg_diesel_tillage_kgCO2e", "herd_feed_farm_ghg_elec_kgCO2e",
     "herd_feed_farm_ghg_ferti_prod_kgCO2e", "herd_feed_farm_ghg_heat_fuel_kgCO2e",
     "herd_feed_farm_N2O_ATD_kgCO2e", "herd_feed_farm_N2O_d_kgCO2e",
     "herd_feed_farm_N2O_L_kgCO2e", "herd_feed_farm_total_ghg_crop_kgCO2e",
     "herd_feed_pseudofarm_ghg_diesel_remain_kgCO2e", "herd_feed_pseudofarm_ghg_diesel_tillage_kgCO2e",
     "herd_feed_pseudofarm_ghg_elec_kgCO2e", "herd_feed_pseudofarm_ghg_ferti_prod_kgCO2e",
     "herd_feed_pseudofarm_ghg_heat_fuel_kgCO2e", "herd_feed_pseudofarm_N2O_ATD_kgCO2e",
     "herd_feed_pseudofarm_N2O_d_kgCO2e", "herd_feed_pseudofarm_N2O_L_kgCO2e",
     "herd_feed_pseudofarm_total_ghg_crop_kgCO2e", "herd_ghg_diesel_remain_kgCO2e",
     "herd_ghg_elec_kgCO2e", "herd_ghg_heat_fuel_kgCO2e", "herd_N2O_D_MM_kgCO2e",
     "herd_N2O_G_mm_kgCO2e", "herd_N2O_L_mm_kgCO2e", "herd_purchased_feed_ghge_kgCO2e",
     "ifthbcref", "Intercept_T", "IPCC_default_values", "IPCC_mix_cat",
     "kcal/kg", "LBOV1_2F_breeders_Fin", "LBOV1_2F_breeders_Fout",
     "LBOV1_2F_breeders_prop", "LBOV1_2F_breeders_Qobs", "LBOV1_2F_CN",
     "LBOV1_2F_fattening_Fin", "LBOV1_2F_fattening_Fout", "LBOV1_2F_fattening_prop",
     "LBOV1_2F_fattening_Qobs", "LBOV1_2F_Fin", "LBOV1_2F_Fout", "LBOV1_2F_ON",
     "LBOV1_2F_PN", "LBOV1_2F_Qeq_milk", "LBOV1_2F_Qobs", "LBOV1_2F_Qobs_meat",
     "LBOV1_2F_Qobs_milk", "LBOV1_2F_SN", "LBOV1_2F_total_downward",
     "LBOV1_2F_total_downward_breeders", "LBOV1_2F_total_downward_fattening",
     "LBOV1_2M_CN", "LBOV1_2M_Fin", "LBOV1_2M_Fout", "LBOV1_2M_ON",
     "LBOV1_2M_PN", "LBOV1_2M_Qobs", "LBOV1_2M_SN", "LBOV1_CN", "LBOV1_Fin",
     "LBOV1_Fout", "LBOV1_ON", "LBOV1_PN", "LBOV1_Qeq_milk", "LBOV1_Qobs",
     "LBOV1_Qobs_meat", "LBOV1_SN", "LBOV2_CN", "LBOV2_Fin", "LBOV2_Fout",
     "LBOV2_ON", "LBOV2_PN", "LBOV2_Qobs", "LBOV2_SN", "LCOWDAIR_Fin",
     "LCOWDAIR_Fout", "LCOWDAIR_PN", "LCOWDAIR_Qobs", "LCOWDAIR_SN",
     "LCOWDAIR_upward_Qobs_milk", "LCOWOTH_CN", "LCOWOTH_Fin", "LCOWOTH_Fout",
     "LCOWOTH_ON", "LCOWOTH_PN", "LCOWOTH_Qobs", "LCOWOTH_SN", "LHEIFBRE_CN",
     "LHEIFBRE_Fin", "LHEIFBRE_Fout", "LHEIFBRE_ON", "LHEIFBRE_PN",
     "LHEIFBRE_Qeq_milk", "LHEIFBRE_Qobs", "LHEIFBRE_Qobs_meat", "LHEIFBRE_SN",
     "LHEIFFAT_CN", "LHEIFFAT_Fin", "LHEIFFAT_Fout", "LHEIFFAT_ON",
     "LHEIFFAT_PN", "LHEIFFAT_Qobs", "LHEIFFAT_SN", "LHENSLAY_CN",
     "LHENSLAY_Fin", "LHENSLAY_Fout", "LHENSLAY_ON", "LHENSLAY_PN",
     "LHENSLAY_Qobs", "LHENSLAY_SN", "lib_ift", "live_weight_kg",
     "livestock", "livestock_enough", "livestock_toomuch", "livestock_unit_coef",
     "LPIGFAT_CN", "LPIGFAT_Fin", "LPIGFAT_Fout", "LPIGFAT_ON", "LPIGFAT_PN",
     "LPIGFAT_Qobs", "LPIGFAT_SN", "LPIGLET_CN", "LPIGLET_Fin", "LPIGLET_Fout",
     "LPIGLET_ON", "LPIGLET_PN", "LPIGLET_Qobs", "LPIGLET_SN", "LPIGOTH_CN",
     "LPIGOTH_Fin", "LPIGOTH_Fout", "LPIGOTH_ON", "LPIGOTH_PN", "LPIGOTH_Qobs",
     "LPIGOTH_SN", "LPLTRBROYL_CN", "LPLTRBROYL_Fin", "LPLTRBROYL_Fout",
     "LPLTRBROYL_ON", "LPLTRBROYL_PN", "LPLTRBROYL_Qobs", "LPLTRBROYL_SN",
     "LPLTROTH_CN", "LPLTROTH_Fin", "LPLTROTH_Fout", "LPLTROTH_ON",
     "LPLTROTH_PN", "LPLTROTH_Qobs", "LPLTROTH_SN", "LSOWBRE_CN",
     "LSOWBRE_Fin", "LSOWBRE_Fout", "LSOWBRE_ON", "LSOWBRE_PN", "LSOWBRE_Qobs",
     "LSOWBRE_SN", "LU", "LU_max", "LU_min", "MCF", "mean_GE_MJ_anim_day",
     "mean_live_weight_kg", "median", "median_all", "median_NUTS2",
     "MFA_dairy_cow", "MFA_ha", "MILK", "milk_t_anim", "MILK_total",
     "MJ/kg", "MMS", "MW", "MY", "N_AG_T", "N_BG_T", "N_ferti_org",
     "N_leach_mms", "N_min", "N_min_ferti_Q", "N_org", "N_retention",
     "N_retention_frac", "N_vol_mms", "N2O_ATD", "N2O_ATD_kgCO2e",
     "N2O_d", "N2O_d_kgCO2e", "N2O_D_MM", "N2O_D_MM_kgCO2e_livcat",
     "N2O_G_mm", "N2O_G_mm_kgCO2e_livcat", "N2O_L", "N2O_L_kgCO2e",
     "N2O_L_mm", "N2O_L_mm_kgCO2e_livcat", "N2ON_ATD", "N2ON_d", "N2ON_L",
     "na.omit", "name", "national_code", "national_suffix", "national_table",
     "nb_climate_reg", "NE_a", "NE_g", "NE_l", "NE_m", "NE_p", "NE_work",
     "needed_in_FADN2Footprint", "Nex_DMI_kgN_anim_y", "Nex_kgN_anim_y",
     "Nex_kgN_livcat_y", "Nin_DMI_kgN_anim_day", "Nin_IPCC_kgN_anim_day",
     "Nmin_th", "Norg_th", "Norg_thrhld_max", "Norg_thrhld_min", "NUTS2",
     "NUTS3", "NZ_feed_DE", "offspring", "offspring_b", "offspring_LSOWBRE",
     "ON", "ORGANIC", "output", "output_e", "parameter", "pattern_FADN",
     "pattern_national", "pesticides", "PFUEL_HEAT", "PFUEL_HEAT_EU",
     "PFUEL_ROAD", "PFUEL_ROAD_EU", "PN", "pop_MMS", "Population__size",
     "practice", "problem", "prod_nb", "prod_t", "prod_t_milk", "Production_seche_volume",
     "prop_sales_Qobs", "prop_sales_Qobs_all", "prop_sales_Qobs_NUTS2",
     "protein_crops_ha", "PRQ", "pseudofarm_area", "pseudofarm_ghge_herd_kgCO2e_livcat",
     "Q_off_farm", "Q_off_farm_meat", "Qeq", "Qeq_b", "Qeq_b_dairy_meat",
     "Qeq_b_meat", "Qeq_b_meat0", "Qeq_eggs", "Qeq_f", "Qeq_f_dairy_meat",
     "Qeq_f_meat", "Qeq_f_meat0", "Qeq_j", "Qeq_j_dairy_meat", "Qeq_j_meat",
     "Qeq_j_meat0", "Qeq_meat", "Qeq_milk", "Qobs", "Qobs_activity",
     "Qobs_activity_LU", "Qobs_b", "Qobs_eggs", "Qobs_f", "Qobs_j",
     "Qobs_LU", "Qobs_LU_act", "Qobs_LU_act_sum", "Qobs_meat", "Qobs_milk",
     "quantile", "raw_flow", "raw_var", "rearing_param", "ref_p100_feed",
     "ref_val", "REG", "rel_weight", "relweight_feed", "REM", "rnorm",
     "RS_T", "rt_f", "rt_j", "rt_LBOV1", "rt_LBOV1_2F_breeders", "rt_LBOV1_2F_fattening",
     "rt_LBOV1_2M", "rt_LBOV2", "rt_LCOWDAIR", "rt_LCOWOTH", "rt_LHEIFBRE",
     "rt_LHEIFFAT", "rt_LPIGFAT", "rt_LPIGLET", "rt_LPIGOTH", "SAA_Agreste_2020",
     "Sailley_feed", "Sailley_livestock", "sales_e", "sales_nb", "sd_GE_MJ_anim_day",
     "setNames", "Shannon", "sigma", "Slope_T", "SN", "source_details",
     "soy_FADN", "soy_Lindner", "species", "SQ", "SRN", "SRV", "SSN",
     "SSV", "suffix", "sum_area_ha", "sum_BVI_ha_feed", "sum_MCF_AWMS",
     "sum_Nmin_th", "sum_sales_e_activity", "sum_sales_e_farm", "sum_sales_e_species",
     "sum_th_DMI_t_livcat_y", "Superficie_correspondante_hectare",
     "SV", "SYS02", "t_DM_feed_concent", "t_DM_feed_produced", "t_DM_feed_purchased",
     "t_DM_panim_fod_maize", "t_DM_panim_soy", "TA", "temp_alu_calc",
     "TF14", "th_crop_value", "th_crop_value_p100_feed_type", "th_DMI_t_livcat_y",
     "th_feed_type_value", "th_total_DMI_t_livcat_y", "threshold_down",
     "threshold_up", "tillage", "TO", "TO_e", "total", "total_GE_MJ",
     "total_ghg_crop_kgCO2e_per_t", "total_sales_e", "total_t_DM",
     "Tourteaux", "UE_GE", "UNFCCC_cat", "unit_conversion", "valid_practice",
     "value_TFI_ha", "var_common", "var_user", "variable", "VS", "VS(2)_daily_excretion_(average)",
     "w_mean", "weight", "Weight", "WG", "wheat_FADN", "wheat_FADN_max",
     "wheat_Lindner", "x_norm", "y", "y_max", "y_min", "year", "YEAR",
     "yield", "yield_e_Qobs", "yield_e_Qobs_all", "yield_e_Qobs_NUTS2",
     "yield_SAA", "yield_SAA_country", "yield_t_Qobs", "yield_t_Qobs_all",
     "yield_t_Qobs_NUTS2", "yield_t_sales_nb", "yield_t_sales_nb_all",
     "yield_t_sales_nb_NUTS2", "Ym",
     "Ash %", "CP %", "GE MJ/kg", "GE kcal/kg"))
